# Generated by Django 4.2.20 on 2025-03-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USDRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd', models.CharField(max_length=100, verbose_name='Курс Доллара')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Курс доллара',
                'verbose_name_plural': 'Курсы доллара',
            },
        ),
    ]
